/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const BetterScroll: typeof import('../components/BetterScroll').default
  const ButtonIcon: typeof import('../components/ButtonIcon').default
  const DarkModeContainer: typeof import('../components/DarkModeContainer').default
  const ErrorBoundary: typeof import('../components/ErrorBoundary').default
  const Fragment: typeof import('react').Fragment
  const FullScreen: typeof import('../components/FullScreen').default
  const IconAntDesignReloadOutlined: typeof import('~icons/ant-design/reload-outlined.tsx').default
  const IconGridiconsFullscreen: typeof import('~icons/gridicons/fullscreen.tsx').default
  const IconGridiconsFullscreenExit: typeof import('~icons/gridicons/fullscreen-exit.tsx').default
  const IconLocalBanner: typeof import('~icons/local/banner.tsx').default
  const IconLocalLogo: typeof import('~icons/local/logo.tsx').default
  const Loading: typeof import('../components/Loading').default
  const MenuToggler: typeof import('../components/MenuToggler').default
  const NumberTicker: typeof import('../components/NumberTicker').default
  const PinToggler: typeof import('../components/PinToggler').default
  const ProTab: typeof import('../components/ProTable').ProTab
  const ProTable: typeof import('../components/ProTable').ProTable
  const SkyrocAvatar: typeof import('../components/SkyrocAvatar').default
  const Suspense: typeof import('react').Suspense
  const SvgIcon: typeof import('../components/SvgIcon').default
  const SystemLogo: typeof import('../components/SystemLogo').default
  const TabEvent: typeof import('../hooks/tab/tabEnum').TabEvent
  const TypingAnimation: typeof import('../components/TypingAnimation').default
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const copy: typeof import('../hooks/common/copy').default
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const emitter: typeof import('../hooks/common/use-emitter').emitter
  const forwardRef: typeof import('react').forwardRef
  const getFixedTabs: typeof import('../hooks/tab/shared').getFixedTabs
  const getRouteIcons: typeof import('../hooks/tab/shared').getRouteIcons
  const getTabByRoute: typeof import('../hooks/tab/shared').getTabByRoute
  const initTab: typeof import('../hooks/tab/useTab').initTab
  const isTabInTabs: typeof import('../hooks/tab/shared').isTabInTabs
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAntdTable: typeof import('ahooks').useAntdTable
  const useArray: typeof import('../hooks/common/use-array').default
  const useAsyncEffect: typeof import('ahooks').useAsyncEffect
  const useBoolean: typeof import('ahooks').useBoolean
  const useCacheTabs: typeof import('../hooks/tab/useTab').useCacheTabs
  const useCallback: typeof import('react').useCallback
  const useClickAway: typeof import('ahooks').useClickAway
  const useContext: typeof import('react').useContext
  const useControllableValue: typeof import('ahooks').useControllableValue
  const useCookieState: typeof import('ahooks').useCookieState
  const useCopy: typeof import('../hooks/common/copy').useCopy
  const useCountDown: typeof import('ahooks').useCountDown
  const useCounter: typeof import('ahooks').useCounter
  const useCreation: typeof import('ahooks').useCreation
  const useCurrentRoute: typeof import('../hooks/router/useCurrentRoute').useCurrentRoute
  const useDebounce: typeof import('ahooks').useDebounce
  const useDebounceEffect: typeof import('ahooks').useDebounceEffect
  const useDebounceFn: typeof import('ahooks').useDebounceFn
  const useDebugValue: typeof import('react').useDebugValue
  const useDeepCompareEffect: typeof import('ahooks').useDeepCompareEffect
  const useDeepCompareLayoutEffect: typeof import('ahooks').useDeepCompareLayoutEffect
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDocumentVisibility: typeof import('ahooks').useDocumentVisibility
  const useDrag: typeof import('ahooks').useDrag
  const useDrop: typeof import('ahooks').useDrop
  const useDynamicList: typeof import('ahooks').useDynamicList
  const useEcharts: typeof import('../hooks/common/echarts').useEcharts
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEmit: typeof import('../hooks/common/use-emitter').useEmit
  const useEventEmitter: typeof import('ahooks').useEventEmitter
  const useEventListener: typeof import('ahooks').useEventListener
  const useEventTarget: typeof import('ahooks').useEventTarget
  const useExternal: typeof import('ahooks').useExternal
  const useFavicon: typeof import('ahooks').useFavicon
  const useFocusWithin: typeof import('ahooks').useFocusWithin
  const useFullscreen: typeof import('ahooks').useFullscreen
  const useFusionTable: typeof import('ahooks').useFusionTable
  const useGetState: typeof import('ahooks').useGetState
  const useHistoryTravel: typeof import('ahooks').useHistoryTravel
  const useHover: typeof import('ahooks').useHover
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInViewport: typeof import('ahooks').useInViewport
  const useInfiniteScroll: typeof import('ahooks').useInfiniteScroll
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInterval: typeof import('ahooks').useInterval
  const useIsomorphicLayoutEffect: typeof import('ahooks').useIsomorphicLayoutEffect
  const useKeyPress: typeof import('ahooks').useKeyPress
  const useLatest: typeof import('ahooks').useLatest
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocalStorageState: typeof import('ahooks').useLocalStorageState
  const useLockFn: typeof import('ahooks').useLockFn
  const useLongPress: typeof import('ahooks').useLongPress
  const useMap: typeof import('ahooks').useMap
  const useMemo: typeof import('react').useMemo
  const useMemoizedFn: typeof import('ahooks').useMemoizedFn
  const useMount: typeof import('ahooks').useMount
  const useMouse: typeof import('ahooks').useMouse
  const useMutationObserver: typeof import('ahooks').useMutationObserver
  const useNetwork: typeof import('ahooks').useNetwork
  const useOn: typeof import('../hooks/common/use-emitter').useOn
  const useOptimistic: typeof import('react').useOptimistic
  const usePagination: typeof import('ahooks').usePagination
  const usePrevious: typeof import('ahooks').usePrevious
  const useRafInterval: typeof import('ahooks').useRafInterval
  const useRafState: typeof import('ahooks').useRafState
  const useRafTimeout: typeof import('ahooks').useRafTimeout
  const useReactive: typeof import('ahooks').useReactive
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useReloadPage: typeof import('../hooks/layout/index').useReloadPage
  const useRequest: typeof import('ahooks').useRequest
  const useResetState: typeof import('ahooks').useResetState
  const useResponsive: typeof import('ahooks').useResponsive
  const useSafeState: typeof import('ahooks').useSafeState
  const useScroll: typeof import('ahooks').useScroll
  const useSelections: typeof import('ahooks').useSelections
  const useSessionStorageState: typeof import('ahooks').useSessionStorageState
  const useSet: typeof import('ahooks').useSet
  const useSetState: typeof import('ahooks').useSetState
  const useSize: typeof import('ahooks').useSize
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTabActions: typeof import('../hooks/tab/useTab').useTabActions
  const useTabController: typeof import('../hooks/tab/useTab').useTabController
  const useTabManage: typeof import('../hooks/tab/useTab').useTabManage
  const useTabScroll: typeof import('../hooks/tab/useTabScroll').useTabScroll
  const useTanstackRouter: typeof import('../hooks/router/useTanstackRouter').useTanstackRouter
  const useTextSelection: typeof import('ahooks').useTextSelection
  const useTheme: typeof import('ahooks').useTheme
  const useThrottle: typeof import('ahooks').useThrottle
  const useThrottleEffect: typeof import('ahooks').useThrottleEffect
  const useThrottleFn: typeof import('ahooks').useThrottleFn
  const useTimeout: typeof import('ahooks').useTimeout
  const useTitle: typeof import('ahooks').useTitle
  const useToggle: typeof import('ahooks').useToggle
  const useTrackedEffect: typeof import('ahooks').useTrackedEffect
  const useTransition: typeof import('react').useTransition
  const useUnmount: typeof import('ahooks').useUnmount
  const useUnmountedRef: typeof import('ahooks').useUnmountedRef
  const useUpdate: typeof import('ahooks').useUpdate
  const useUpdateEffect: typeof import('ahooks').useUpdateEffect
  const useUpdateLayoutEffect: typeof import('ahooks').useUpdateLayoutEffect
  const useVirtualList: typeof import('ahooks').useVirtualList
  const useWebSocket: typeof import('ahooks').useWebSocket
  const useWhyDidYouUpdate: typeof import('ahooks').useWhyDidYouUpdate
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC } from 'react'
  import('react')
  // @ts-ignore
  export type { ECOption } from '../hooks/common/echarts'
  import('../hooks/common/echarts')
  // @ts-ignore
  export type { TabEvent } from '../hooks/tab/tabEnum'
  import('../hooks/tab/tabEnum')
  // @ts-ignore
  export type { ProColumn } from '../components/ProTable'
  import('../components/ProTable')
}
