/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutHomeIndexRouteImport } from './routes/_layout/home/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'
import { Route as LayoutDemoTanstackQueryRouteImport } from './routes/_layout/demo/tanstack-query'
import { Route as LayoutDemoStoreRouteImport } from './routes/_layout/demo/store'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeIndexRoute = LayoutHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoTanstackQueryRoute = LayoutDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoStoreRoute = LayoutDemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/demo/store': typeof LayoutDemoStoreRoute
  '/demo/tanstack-query': typeof LayoutDemoTanstackQueryRoute
  '/about': typeof LayoutAboutIndexRoute
  '/home': typeof LayoutHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/demo/store': typeof LayoutDemoStoreRoute
  '/demo/tanstack-query': typeof LayoutDemoTanstackQueryRoute
  '/about': typeof LayoutAboutIndexRoute
  '/home': typeof LayoutHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/demo/store': typeof LayoutDemoStoreRoute
  '/_layout/demo/tanstack-query': typeof LayoutDemoTanstackQueryRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/home/': typeof LayoutHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/about'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/about'
    | '/home'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/login/'
    | '/_layout/demo/store'
    | '/_layout/demo/tanstack-query'
    | '/_layout/about/'
    | '/_layout/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home/': {
      id: '/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/tanstack-query': {
      id: '/_layout/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof LayoutDemoTanstackQueryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/store': {
      id: '/_layout/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof LayoutDemoStoreRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDemoStoreRoute: typeof LayoutDemoStoreRoute
  LayoutDemoTanstackQueryRoute: typeof LayoutDemoTanstackQueryRoute
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutHomeIndexRoute: typeof LayoutHomeIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDemoStoreRoute: LayoutDemoStoreRoute,
  LayoutDemoTanstackQueryRoute: LayoutDemoTanstackQueryRoute,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutHomeIndexRoute: LayoutHomeIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
